### ISSUE TITLE
Allow Dockerfile to accept argument to clear chain state and insert keys

### ISSUE THREAD

**Issue by lovesh** [docknetwork/dock-substrate#13]

**Comment by bddap** [comment]
Since f7f39dede4cc2319d851f34f3df33529c9dcdbc9 was merged, `--purge-chain` can now be passed to the docker container as requested.

The `insert keys` solution probably is not exactly what you were hoping for, but #30 includes a key_upload script in the final docker image. Key upload is still a bit of a pain but is is possible. This can be made more ergonomic but it would take some dev effort.

Closing this issue. @lovesh Please re-open if you think it should be re-opened.
